# Fase de build
FROM node as build
RUN npm i npm@8.11.0 -g
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package*.json ./ 
RUN npm ci --no-optional && npm cache clean --force
COPY . .
RUN npm run build

# Fase de production
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
